### ISSUE TITLE
CLI Tool for smart contracts' deployment

### ISSUE THREAD

**Issue by miloszm** [dusk-network/dusk-deploy-cli#1]
We need a tool which will allow the user to deploy a contract into a Dusk blockchain.
The tool should:

- accept a contract in a file form (a .wasm file),
- ask user for additional information
- deploy the contract into blockchain
- inform the user about success or give out error information
- display help information

This issue is part of epic https://github.com/dusk-network/rusk/issues/1071 (Add Contract Deployment System)

**Comment by HDauven** [comment]
Closing, fixed in: https://github.com/dusk-network/dusk-deploy-cli/pull/3
